import express from 'express'
import crypto from 'node:crypto'
import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import bcrypt from 'bcryptjs'
import { put, del } from '@vercel/blob'
const root=path.dirname(fileURLToPath(import.meta.url)), dataDir=path.join(root,'data'), file=path.join(dataDir,'store.json'), port=Number(process.env.PORT||8787)
const OWNER_EMAIL=String(process.env.OWNER_EMAIL||'ynr.location@gmail.com').trim().toLowerCase()
const OWNER_PASSWORD_HASH=process.env.OWNER_PASSWORD_HASH||'$2b$12$rc/J4DF6HAznQhX5.n9voeo82H3QqymCfkWUUE21WlFiCPOqvOb/G'
const defaults={settings:{brand:'YNR Luxury Rent',tagline:'Location de véhicules premium pour professionnels et particuliers',phone:'06 48 02 37 74 · 07 45 45 41',whatsapp:'33648023774',email:'ynr.location@gmail.com',instagram:'https://instagram.com/ynr_location',snapchat:'https://t.snapchat.com/ECABDZ05'},vehicles:[{id:'v1',name:'BMW M3 Competition',category:'Berline sportive',price:490,deposit:3000,description:'Une sportive précise et confortable pour les trajets professionnels comme les escapades du week-end.',photos:['https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=85'],active:true}],requests:[],blocked:[]}
let memoryStore=structuredClone(defaults);const clean=(v,max=1000)=>typeof v==='string'?v.trim().slice(0,max):''
const sessionSecret=process.env.SESSION_SECRET||'ynr-production-session-secret-change-me';const signSession=exp=>{const value=String(exp),sig=crypto.createHmac('sha256',sessionSecret).update(value).digest('hex');return `${value}.${sig}`};const validSession=t=>{const [exp,sig]=String(t||'').split('.'),expected=crypto.createHmac('sha256',sessionSecret).update(exp||'').digest('hex');return Boolean(exp&&sig&&Number(exp)>Date.now()&&sig.length===expected.length&&crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected)))}
async function read(){try{return JSON.parse(await fs.readFile(file,'utf8'))}catch{return structuredClone(memoryStore)}}
async function write(v){memoryStore=structuredClone(v);try{await fs.mkdir(dataDir,{recursive:true});const tmp=`${file}.tmp`;await fs.writeFile(tmp,JSON.stringify(v,null,2));await fs.rename(tmp,file)}catch(error){if(process.env.VERCEL)console.warn('[v0] Using memory store on Vercel:',error.code);else throw error}}
function auth(req,res,next){const t=req.headers.cookie?.match(/ynr_session=([^;]+)/)?.[1];if(!validSession(t))return res.status(401).json({message:'Authentification requise'});req.session=t;next()}
const app=express();app.use(express.json({limit:'25mb'}));app.use(express.static(path.join(root,'dist')))
app.post('/api/uploads',auth,async(req,res)=>{try{const data=String(req.body?.data||''),match=data.match(/^data:(image\/(?:jpeg|png|webp));base64,([A-Za-z0-9+/=]+)$/);if(!match)return res.status(400).json({message:'Image JPEG, PNG ou WEBP requise'});const raw=Buffer.from(match[2],'base64');if(raw.length>8*1024*1024)return res.status(413).json({message:'Image trop volumineuse (8 Mo maximum)'});const ext=match[1].split('/')[1].replace('jpeg','jpg'),name=`vehicles/${crypto.randomUUID()}.${ext}`,blob=await put(name,raw,{access:'public',contentType:match[1]});res.status(201).json({url:blob.url})}catch(error){console.error('[v0] Blob upload failed',error);res.status(500).json({message:'Upload cloud indisponible'})}})
app.get('/api/public',async(_,res)=>{const s=await read();res.json({settings:s.settings,vehicles:s.vehicles.filter(v=>v.active),blocked:s.blocked})})
app.get('/api/health',(_,res)=>res.json({ok:true}))
app.post('/api/auth/login',async(req,res)=>{const email=clean(req.body?.email,180).toLowerCase(),pw=String(req.body?.password||'');let valid=Boolean(email===OWNER_EMAIL&&await bcrypt.compare(pw,OWNER_PASSWORD_HASH));if(!valid)return res.status(401).json({message:'Identifiants invalides'});const t=signSession(Date.now()+86400000);res.setHeader('Set-Cookie',`ynr_session=${t}; HttpOnly; SameSite=Lax; Secure; Path=/; Max-Age=86400`);res.json({ok:true})})
app.get('/api/auth/session',auth,(req,res)=>res.json({ok:true}));app.post('/api/auth/logout',auth,(req,res)=>{res.setHeader('Set-Cookie','ynr_session=; HttpOnly; SameSite=Lax; Secure; Path=/; Max-Age=0');res.status(204).end()})
app.get('/api/admin',auth,async(_,res)=>res.json(await read()))
app.post('/api/requests',async(req,res)=>{const b=req.body||{};if(!clean(b.name,120)||!clean(b.email,180)||!clean(b.vehicle,120)||!clean(b.start,20)||!clean(b.end,20))return res.status(400).json({message:'Veuillez compléter les champs obligatoires.'});const s=await read(),item={id:crypto.randomUUID(),name:clean(b.name,120),email:clean(b.email,180),phone:clean(b.phone,40),type:b.type==='professionnel'?'professionnel':'particulier',vehicle:clean(b.vehicle,120),start:clean(b.start,20),end:clean(b.end,20),message:clean(b.message,1500),status:'nouvelle',createdAt:new Date().toISOString()};s.requests.unshift(item);await write(s);res.status(201).json(item)})
app.patch('/api/requests/:id',auth,async(req,res)=>{const s=await read(),r=s.requests.find(x=>x.id===req.params.id);if(!r)return res.sendStatus(404);r.status=['nouvelle','en_cours','traitee'].includes(req.body.status)?req.body.status:r.status;await write(s);res.json(r)})
app.delete('/api/requests/:id',auth,async(req,res)=>{const s=await read();s.requests=s.requests.filter(x=>x.id!==req.params.id);await write(s);res.sendStatus(204)})
app.post('/api/vehicles',auth,async(req,res)=>{const b=req.body||{},s=await read();const v={id:crypto.randomUUID(),name:clean(b.name,120),category:clean(b.category,80),price:Math.max(0,Number(b.price)||0),deposit:Math.max(0,Number(b.deposit)||0),description:clean(b.description,1500),photos:Array.isArray(b.photos)?b.photos.slice(0,8).map(x=>clean(x,200000)):[],active:b.active!==false,updatedAt:new Date().toISOString()};if(!v.name)return res.status(400).json({message:'Nom requis'});s.vehicles.unshift(v);await write(s);res.status(201).json(v)})
app.patch('/api/vehicles/:id',auth,async(req,res)=>{const s=await read(),v=s.vehicles.find(x=>x.id===req.params.id);if(!v)return res.sendStatus(404);Object.assign(v,{name:clean(req.body.name,120)||v.name,category:clean(req.body.category,80)||v.category,price:Math.max(0,Number(req.body.price??v.price)),deposit:Math.max(0,Number(req.body.deposit??v.deposit)),description:clean(req.body.description,1500),photos:Array.isArray(req.body.photos)?req.body.photos.slice(0,8):v.photos,active:req.body.active!==undefined?Boolean(req.body.active):v.active,updatedAt:new Date().toISOString()});await write(s);res.json(v)})
app.delete('/api/vehicles/:id',auth,async(req,res)=>{const s=await read(),vehicle=s.vehicles.find(x=>x.id===req.params.id);if(vehicle?.photos?.length){await Promise.all(vehicle.photos.filter(x=>x.startsWith('https://')).map(x=>del(x).catch(()=>null)))}s.vehicles=s.vehicles.filter(x=>x.id!==req.params.id);await write(s);res.sendStatus(204)})
app.put('/api/calendar',auth,async(req,res)=>{const s=await read();s.blocked=Array.isArray(req.body)?req.body.filter(x=>x.vehicleId&&x.start&&x.end).slice(0,500):[];await write(s);res.json(s.blocked)})
app.put('/api/settings',auth,async(req,res)=>{const s=await read();s.settings={...s.settings,...Object.fromEntries(Object.entries(req.body||{}).map(([k,v])=>[k,clean(v,500)]))};await write(s);res.json(s.settings)})
app.use((_,res)=>res.sendFile(path.join(root,'dist','index.html')))
if(!process.env.VERCEL) app.listen(port,()=>console.log(`[YNR] API listening on ${port}`))
export default app
